@startuml
title Podcast Index 2.0 infra

skinparam node {
    BackgroundColor #FFFFD0
    BackgroundColor<<host>> #e92626
    BackgroundColor<<linode>> #80a0ff
}

skinparam cloud {
    BackgroundColor<<cdn>> #f38020 
}


left to right direction
cloud mailgun {

}

cloud voltageNode {

}

cloud cloudflare <<cdn>> {
  rectangle sni
  node cloudflare00 <<cdn>> {
    rectangle roundRobin
  }
  node cloudflare01 <<cdn>> {

  }
}

node linode <<linode>> as "Podcast Index" {

  package frontEnd {
    node apiServer00 <<host>> as "API Server00\n(Ubuntu20.04)\nx2" {
      rectangle apiServer00a as "nginx\nPHP FPM"
      
    }

    node webSrv <<host>> as "Podcast Index Web Server\nSmall Linode\n(Ubuntu20.04)" {
      rectangle webSrva as "https://podcastindex.org/\nnginx\nPHP FPM"
    }
  }
  node dbserver <<host>> as "DB\n(Ubuntu20.04)" {
      database dbSrv <<mysql8>> as "Podcast Index DB" {
        
      }
      rectangle volume00 as "640GB DB storage"
      rectangle ram00 as "32DB"
  }
  package "Aggregators" {
    node aggSmall <<host>> as "Aggregators \n1GB nanode $5month\n(Ubuntu20.04)\n 6x" {
      rectangle aggSmallb as "PartyTime\nPuller to pull feed"

    }
    node aggMed <<host>> as "Aggregators 2GB Linodes\n 3x" {
      rectangle aggMeda as "PartyTime\nPuller to pull feed"

    }
  }
  package "Search Indexers" {
    node searchIndexer00 <<host>> as "Main Indexer\n 3x\n(Ubuntu20.04)" {
      rectangle searchIndexer00a as "Pulls DB every 15 to 20 minutes\nSphinx Manitcore\nIndexes the title, and author of the feed"
    }
    node searchIndexer01 <<host>> as "Sphinx Manitcore\n(Ubuntu20.04)" {
      rectangle searchIndexer01a as "Sphinx Manitcore\nIndexes the Person search"
      
    }
    node searchIndexer02 <<host>> as "Sphinx Manitcore\n(Ubuntu20.04)" {
      rectangle searchIndexer02a as "Sphinx Manitcore\nAutocomplete"
    }
    node searchIndexer03 <<host>> as "Sphinx Manitcore\n(Ubuntu20.04)" {
      rectangle searchIndexer03a as "Sphinx Manitcore\nValue for value search"
    }
  }
  package "Utility" {
 
    node utilitySrv00 <<host>> as "Utility Mail\n1GB nanode $5month\n(Ubuntu20.04)" {
      rectangle mail00  as "Mail bastion host\nAll mail goes through this host\n then sent to mailgun" 
    }
    node utilitySrv01 <<host>> as "Utility Backup\n4G linode\n(Ubuntu20.04)" {
      rectangle utilitySrv01a as "Backups\nnightly, weekly, monthly\nMonitoring podping\nDB flags when things need to polled\nUtility work\ncron jobs\npruning, slow polling, weekly db dumps"
    }
    node utilitySrv02 <<host>> as "Utility Webhook gateway\n1GB nanode $5month\n(Ubuntu20.04)" {
      rectangle utilitySrv02a as "Sovereign Feed\nWebhook gateway or any webhook traffic\nUnlocks Podcast Index Lightning Node"  
    }
    node ligthnginUtilitySrv00 <<host>> as "Utility Lightning\n1GB nanode $5month\n(Ubuntu20.04)" {
      rectangle ligthnginUtilitySrv00a as "Lightning node maintenance\nLightning node other tasks\nPolls once a minutes\nPolls node trancations\ngenerating charts\nweeklyboostagrams\nrunning total\ndumps to a MySQL DB"
    }
    node podping00 <<host>> as "Podping\n1GB nanode $5month\n(Ubuntu20.04)\nx5" {
      rectangle podping00a as "Australia\nEurope\n3x US by region"
    }
    node activityPubBridge00 <<host>> as "ActivityPub Bridge\n2GB linode $10month\n(Ubuntu20.04)" {
      rectangle activityPubBridge00a as "ActivityPub Bridge"
    }
    node testingSrv00 <<host>> as "Genral testing and work\n1GB nanode $5month\n(Ubuntu20.04)" {
      rectangle testingSrv00a as "Testing and new work"
    }
  }
  cloudflare00 --> apiServer00
  cloudflare01 --> webSrv
  webSrv --> dbserver
  aggSmall --> dbserver
  aggMed   --> dbserver
  searchIndexer00 --> dbserver
  searchIndexer01 --> dbserver
  searchIndexer02 --> dbserver
  searchIndexer03 --> dbserver
  utilitySrv01 --> dbserver
}


utilitySrv00 --> mailgun
ligthnginUtilitySrv00 --> voltageNode
@enduml