@startuml pi2.0_all

title Podcast Index 2.0 infra

skinparam node {
    BackgroundColor #FFFFD0
    BackgroundColor<<host>> #74a8dc
}

skinparam cloud {
    BackgroundColor<<user>> #69c890
    BackgroundColor<<api>> #f4a24f
    BackgroundColor<<cdn>> #69c890

    BackgroundColor<<vps>> #69c890
  
}
cloud internet {

}
cloud mailgun {}

node cloudflare <<cdn>> {
  rectangle sni
  node cloudflare00 <<cdn>> {
    rectangle roundRobin
  }
  node cloudflare01 <<cdn>> {

  }
}

node linode <<vps>> as "Podcast Index" {


  node apiServer00 <<host>> as "API Server00\n(Ubuntu22.04)" {

      rectangle api_nginx_reverse_proxy00 as "api.podcastindex.org"
      rectangle fpm00 as "PHP FPM"
  }
  node apiServer01 <<host>> as "API Server01\n(Ubuntu22.04)" {
      rectangle api_nginx_reverse_proxy01 as "api.podcastindex.org"
      rectangle fpm01 as "PHP FPM"
  }

  node dbserver <<host>> as "DB\n(Ubuntu22.04)" {
      database dbSrv <<mysql8>> as "Podcast Index DB" {
        
      }
      rectangle volume00 as "640GB DB storage"
      rectangle ram00 as "32DB"
  }

  node webSrv <<host>> as "Podcast Index Web Server\nSmall Linode\n(Ubuntu22.04)" {
    node webSite00 as "https://podcastindex.org/" {
      
    }
  }

  node aggSmall <<host>> as "Aggregators \n1GB nanode $5month\n(Ubuntu22.04)\n 6x"{
    rectangle partyTime00 as PartyTime
    rectangle puller00 as "Puller to pull feed"

  }
  node aggMed <<host>> as "Aggregators 2GB Linodes\n 3x"{
    rectangle partyTime00 as PartyTime
    rectangle puller00 as "Puller to pull feed"

  }
  node searchIndexer00 <<host>> as "Main Indexer\n 3x\n(Ubuntu22.04)" {
    rectangle pulls00 as "Pulls DB every 15 to 20 minutes"
    rectangle sphinx00 as "Sphinx Manitcore"
    rectangle siNote00 as "Indexes the title, and author of the feed"
  }
  node searchIndexer01 <<host>> as "si01\n(Ubuntu22.04)" {
    rectangle sphinx01 as "Sphinx Manitcore"
    rectangle siNote01 as "Indexes the Person search"
    
  }
  node searchIndexer02 <<host>> as "Sphinx Manitcore\n(Ubuntu22.04)" {
    rectangle sphinx02 as "Sphinx Manitcore"
    rectangle siNote02 as "Autocomplete"
  }
  node searchIndexer3 <<host>> as "Sphinx Manitcore\n(Ubuntu22.04)" {
    rectangle sphinx03 as "Sphinx Manitcore"
    rectangle siNote03 as "Value for value search"
  }

  node utilitySrv00 <<host>> as "Utility Mail\n1GB nanode $5month\n(Ubuntu22.04)" {
    rectangle mail00  as "Mail bastion host\nAll mail goes through this host\n then sent to mailgun" 
  }
  node utilitySrv01 <<host>> as "Utility Backup\n4G linode\n(Ubuntu22.04)" {
    rectangle us01a as "Backups\nnightly, weekly, monthly"
    rectangle us01b as "Monitoring podping"
    rectangle us01c as "DB flags when things need to polled"
    rectangle us01d as "Utility work\ncron jobs\npruning, slow polling, weekly db dumps"
  }
  node utilitySrv02 <<host>> as "Utility Webhook gateway\n1GB nanode $5month\n(Ubuntu22.04)" {
    rectangle us02a as "Sovereign Feed\nWebhook gateway or any webhook traffic"
    rectangle us02b as "Unlocks Podcast Index Lightning Node"  
  }
  node ligthnginUtilitySrv <<host>> as "Utility Lightning\n1GB nanode $5month\n(Ubuntu22.04)" {
    rectangle lightning00 as "Lightning node maintenance\nLightning node other tasks\nPolls once a minutes\nPolls node trancations"
    rectangle lightning01 as "Lightning node other tasks; generating charts\nweeklyboostagrams\nrunning total\ndumps to a MySQL DB"
  }
  node podping00 <<host>> as "Podping\n1GB nanode $5month\n(Ubuntu22.04)\nx5" {
    rectangle podping00a as "Australia\nEurope\n3x US by region"

  }
  node activityPubBridge00 <<host>> as "ActivityPub Bridge\n2GB linode $10month\n(Ubuntu22.04)" {
    rectangle activityPub00 as "ActivityPub Bridge"
  }
  node testingSrv00 <<host>> as "Genral testing and work\n1GB nanode $5month\n(Ubuntu22.04)" {
    rectangle testing00 as "Testing and new work"
  }

   
}


[internet] --> [cloudflare00]
[cloudflare00] --> [apiServer00]
[cloudflare00] --> [apiServer01]

[api_nginx_reverse_proxy00] --> [fpm00]
[api_nginx_reverse_proxy01] --> [fpm01]

[apiServer00] --> [dbserver]
[apiServer01] --> [dbserver]

[cloudflare01] --> [webSrv]
webSrv --> dbserver

aggSmall --> internet
aggSmall --> dbserver

aggMed --> internet
aggMed --> dbserver

searchIndexer00 --> internet
searchIndexer01 --> internet
searchIndexer02 --> internet
searchIndexer03 --> internet

searchIndexer00 --> dbserver
searchIndexer01 --> dbserver
searchIndexer02 --> dbserver
searchIndexer03 --> dbserver

utilitySrv00 --> mailgun
utilitySrv00 --> internet

utilitySrv01 --> internet
utilitySrv01 --> dbserver


@enduml